"""What the shop answers about itself over HTTP: whether it is up, what it
logged, and its figures in the text Prometheus scrapes.

The routes are the shop's; what they report is handed in. The shop keeps no
counters of its own - its minutes are generated by whatever runs it - so the
lines and the exposition arrive as callables, and this module never learns
where they come from. That keeps the dependency pointing one way: `target_app`
knows the shop, and the shop knows nothing about the rig.
"""

from __future__ import annotations

from collections.abc import Callable

from fastapi import APIRouter
from fastapi.responses import PlainTextResponse


def the_shops_routes(log_lines: Callable[[], list[str]],
                     exposition: Callable[[], str],
                     exposition_content_type: str) -> APIRouter:
    """`/health`, `/logs` and `/metrics`, answering from what is handed in."""
    routes = APIRouter()

    @routes.get("/health")
    def health() -> dict[str, str]:
        return {"status": "ok"}

    @routes.get("/logs", response_model=list[str])
    def logs() -> list[str]:
        return log_lines()

    @routes.get("/metrics")
    def metrics() -> PlainTextResponse:
        return PlainTextResponse(exposition(), media_type=exposition_content_type)

    return routes
